version: '3.7'
services:
# Database Service (Mysql)
  icts-mysql:
    container_name: icts-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: lojavirtual
      MYSQL_USER: luiz
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  backend:
    image: 'maven:3-jdk-8-alpine'
    volumes:
     - ./lojavirtual:/app/
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=prod
    working_dir: /app
    ports:
     - 8080:8080
    depends_on:
     - icts-mysql

  frontend:
    image: 'node:lts-alpine'
    volumes:
     - ./lojavirtual_web:/app/
    command: sh -c "(npm i && npm run build) && node server.js"
    working_dir: /app
    ports:
     - 3000:3000

